# Generated by Django 5.2.4 on 2025-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('scenario', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
